name: fe CI/CD work-flow

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "fe/**"
  push:
    branches:
      - develop
      - main
    paths:
      - "fe/**"

jobs:
  build-develop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: install packages
        working-directory: ./fe
        run: npm install
      - name: build next
        working-directory: ./fe
        run: npm run build
